Diplom: Field Class Reference
Field Class Reference
Field class.
Public Member Functions
__init__ (self, length_m, width_m, rows, cols, rx, ry, alpha, beta, Wm, Deltat, line=None, field=None)
Constructor for Field class.
calc_base (self, func, a=2, b=0.3, c=3)
Calculate the base value of the field.
__getitem__ (self, index)
__setitem__ (self, index, value)
__str__ (self)
randomize_field (self, MAX_V=0.4123, MIN_V=0.0)
Randomize the field.
avg_field (self, field=None)
Calculate the average water level in the field.
update_cell (self, r, c, x, w, v)
Update the moisture level of a cell in the field.
parallel_update_field (self, x, w, v)
Data Fields
rows = rows
cols = cols
rx = rx
ry = ry
alpha = alpha
beta = beta
Wm = Wm
Deltat = Deltat
int line = line if line is not None else self.rows // 2
field = field if field is not None else self.randomize_field()
length_m = length_m
width_m = width_m
cell_length_m = length_m / cols
cell_width_m = width_m / rows
rx_cells = int(self.rx / self.cell_length_m)
ry_cells = int(self.ry / self.cell_width_m)
Detailed Description
Field class.
Class for representing a field with a grid of cells.
Definition at line 14 of file Field.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, length_m, width_m, rows, cols, rx, ry, alpha, beta, Wm, Deltat, line = None, field = None)
Constructor for Field class.
Parameters
length_m Length of the field in meters.
width_m Width of the field in meters.
rows Number of rows in the field.
cols Number of columns in the field.
rx Radius of watering in meters.
ry Radius of watering in meters.
alpha Coefficient for watering.
beta Coefficient for watering.
Wm Maximum watering in meters.
Deltat Time step.
line Line index of watering machine.
field 2D np.array, optional
Initializes the field with the given parameters and sets the moisture level of each cell to a random value between 0 and 1.
Definition at line 21 of file Field.py.
References alpha, beta, cell_length_m, cell_width_m, cols, Deltat, field, length_m, line, randomize_field(), rows, rx, rx_cells, ry, ry_cells, width_m, and Wm.
Member Function Documentation
__getitem__()
__getitem__ (self, index)
Definition at line 76 of file Field.py.
__setitem__()
__setitem__ (self, index, value)
Definition at line 82 of file Field.py.
__str__()
__str__ (self)
Definition at line 91 of file Field.py.
avg_field()
avg_field (self, field = None)
Calculate the average water level in the field.
Parameters
field 2D np.array, optional
Calculates the average water level in the field.
Returns
float
Definition at line 111 of file Field.py.
References field.
calc_base()
calc_base (self, func, a = 2, b = 0.3, c = 3)
Calculate the base value of the field.
Parameters
func Function to calculate the base value.
a Parameter a.
b Parameter b.
c Parameter c.
Definition at line 63 of file Field.py.
References field.
parallel_update_field()
parallel_update_field (self, x, w, v)
@param x Current position of watering machine.
@param w Watering intensity.
@param v Water level.
@return List of changes in the field.
@details Updates the moisture level of cells in the field based on the current position of the watering machine, the watering intensity, and the water level.
Definition at line 148 of file Field.py.
References cols, line, rows, rx_cells, ry_cells, and update_cell().
randomize_field()
randomize_field (self, MAX_V = 0.4123, MIN_V = 0.0)
Randomize the field.
Parameters
MAX_V Maximum water level.
MIN_V Minimum water level.
Definition at line 98 of file Field.py.
References cols, field, line, and rows.
Referenced by __init__().
update_cell()
update_cell (self, r, c, x, w, v)
Update the moisture level of a cell in the field.
Parameters
r Row index of the cell.
c Column index of the cell.
x Current position of watering machine.
w Watering intensity.
v Water level.
Returns
float
Updates the moisture level of a cell in the field based on the current position of the watering machine, the watering intensity, and the water level.
Definition at line 126 of file Field.py.
References alpha, beta, Deltat, field, line, and Wm.
Referenced by parallel_update_field().
Field Documentation
alpha
alpha = alpha
Definition at line 48 of file Field.py.
Referenced by __init__(), and update_cell().
beta
beta = beta
Definition at line 49 of file Field.py.
Referenced by __init__(), and update_cell().
cell_length_m
cell_length_m = length_m / cols
Definition at line 56 of file Field.py.
Referenced by __init__().
cell_width_m
cell_width_m = width_m / rows
Definition at line 57 of file Field.py.
Referenced by __init__().
cols
cols = cols
Definition at line 45 of file Field.py.
Referenced by __init__(), parallel_update_field(), and randomize_field().
Deltat
Deltat = Deltat
Definition at line 51 of file Field.py.
Referenced by __init__(), and update_cell().
field
field = field if field is not None else self.randomize_field()
Definition at line 53 of file Field.py.
Referenced by __init__(), avg_field(), calc_base(), randomize_field(), and update_cell().
length_m
length_m = length_m
Definition at line 54 of file Field.py.
Referenced by __init__().
line
int line = line if line is not None else self.rows // 2
Definition at line 52 of file Field.py.
Referenced by __init__(), parallel_update_field(), randomize_field(), and update_cell().
rows
rows = rows
Definition at line 44 of file Field.py.
Referenced by __init__(), parallel_update_field(), and randomize_field().
rx
rx = rx
Definition at line 46 of file Field.py.
Referenced by __init__().
rx_cells
rx_cells = int(self.rx / self.cell_length_m)
Definition at line 58 of file Field.py.
Referenced by __init__(), and parallel_update_field().
ry
ry = ry
Definition at line 47 of file Field.py.
Referenced by __init__().
ry_cells
ry_cells = int(self.ry / self.cell_width_m)
Definition at line 59 of file Field.py.
Referenced by __init__(), and parallel_update_field().
width_m
width_m = width_m
Definition at line 55 of file Field.py.
Referenced by __init__().
Wm
Wm = Wm
Definition at line 50 of file Field.py.
Referenced by __init__(), and update_cell().
The documentation for this class was generated from the following file:
Field.py