Diplom: Funcs Namespace Reference
Funcs Namespace Reference
Functions for the optimization of the goal function.
Functions
exp_step (l_0, step, lmbda=0.05)
Exponential step.
poly_step (l_0, step, alpha=0.5, beta=1)
Polynomial step.
base (Field, a, b, c)
Base function.
Gk (Field, x_cur, w, v, t_k, eta, Wm, Deltat, delta, rx, ry, ry_cells, Line, a, b, c_, alpha, beta, gamma, lmbda, Water=0)
Goal function.
dGkdw (Field, x_cur, w, v, t_k, eta, Wm, Deltat, delta, rx, ry, ry_cells, Line, a, b, alpha, beta, Water=0)
Derivative of the goal function.
dGkdv (Field, x_cur, w, v, t_k, eta, Wm, Deltat, delta, rx, ry, ry_cells, Line, a, b, alpha, beta, gamma, lmbda, Water=0)
Derivative of the goal function.
plot_Gk (Field, x_cur, t_k, eta, Wm, Deltat, delta, rx, ry, ry_cells, Line, a, b, c_, alpha, beta, gamma, lmbda, points=None)
Plot the goal function.
Variables
Loader = ConfigLoader('../config.ini')
a
b
c
wp
v
ms
mr
wm
alpha
beta
lmbda
eta
gamma
delta
length_m
width_m
rows
cols
rx
ry
Deltat = Loader.getfloat("Model", "deltat")
field = Field(length_m=length_m, width_m=width_m, rows = rows, cols = cols, rx = rx, ry = ry, alpha = alpha, beta = beta, Wm = wm, Deltat = Deltat)
Detailed Description
Functions for the optimization of the goal function.
Function Documentation
base()
base (Field, a, b, c)
Base function.
Parameters
Field Field.
a A.
b B.
c C.
Definition at line 36 of file Funcs.py.
dGkdv()
dGkdv (Field, x_cur, w, v, t_k, eta, Wm, Deltat, delta, rx, ry, ry_cells, Line, a, b, alpha, beta, gamma, lmbda, Water = 0)
Derivative of the goal function.
Parameters
Field Field.
x_cur Current x.
w W.
v V.
t_k T_k.
eta Eta.
Wm Wm.
Deltat Delta t.
delta Delta.
rx Rx.
ry Ry.
ry_cells Ry cells.
Line Line.
a A.
b B.
alpha Alpha.
beta Beta.
gamma Gamma.
lmbda Lambda.
Water Water.
Returns
Derivative of the goal function.
Definition at line 150 of file Funcs.py.
Referenced by GradientOptimizer.Gradient_Max_step().
dGkdw()
dGkdw (Field, x_cur, w, v, t_k, eta, Wm, Deltat, delta, rx, ry, ry_cells, Line, a, b, alpha, beta, Water = 0)
Derivative of the goal function.
Parameters
Field Field.
x_cur Current x.
w W.
v V.
t_k T_k.
eta Eta.
Wm Wm.
Deltat Delta t.
delta Delta.
rx Rx.
ry Ry.
ry_cells Ry cells.
Line Line.
a A.
b B.
alpha Alpha.
beta Beta.
Water Water.
Returns
Derivative of the goal function.
Definition at line 105 of file Funcs.py.
Referenced by GradientOptimizer.Gradient_Max_step().
exp_step()
exp_step (l_0, step, lmbda = 0.05)
Exponential step.
Parameters
l_0 Initial value.
step Step.
lmbda Lambda.
Definition at line 13 of file Funcs.py.
Referenced by GradientOptimizer.Gradient_Max_step().
Gk()
Gk (Field, x_cur, w, v, t_k, eta, Wm, Deltat, delta, rx, ry, ry_cells, Line, a, b, c_, alpha, beta, gamma, lmbda, Water = 0)
Goal function.
Parameters
Field Field.
x_cur Current x.
w W.
v V.
t_k T_k.
eta Eta.
Wm Wm.
Deltat Delta t.
delta Delta.
rx Rx.
ry Ry.
ry_cells Ry cells.
Line Line.
a A.
b B.
c_ C.
alpha Alpha.
beta Beta.
gamma Gamma.
lmbda Lambda.
Water Water.
Returns
Goal function.
Definition at line 55 of file Funcs.py.
Referenced by plot_Gk().
plot_Gk()
plot_Gk (Field, x_cur, t_k, eta, Wm, Deltat, delta, rx, ry, ry_cells, Line, a, b, c_, alpha, beta, gamma, lmbda, points = None)
Plot the goal function.
Parameters
Field Field.
x_cur Current x.
t_k T_k.
eta Eta.
Wm Wm.
Deltat Delta t.
delta Delta.
rx Rx.
ry Ry.
ry_cells Ry cells.
Line Line.
a A.
b B.
c_ C.
alpha Alpha.
beta Beta.
gamma Gamma.
lmbda Lambda.
points Points to plot.
Returns
None.
Definition at line 198 of file Funcs.py.
References Gk(), and plot_Gk().
Referenced by plot_Gk().
poly_step()
poly_step (l_0, step, alpha = 0.5, beta = 1)
Polynomial step.
Parameters
l_0 Initial value.
step Step.
alpha Alpha.
beta Beta.
Definition at line 24 of file Funcs.py.
Variable Documentation
a
a
Definition at line 254 of file Funcs.py.
alpha
alpha
Definition at line 254 of file Funcs.py.
b
b
Definition at line 254 of file Funcs.py.
beta
beta
Definition at line 254 of file Funcs.py.
c
c
Definition at line 254 of file Funcs.py.
cols
cols
Definition at line 256 of file Funcs.py.
delta
delta
Definition at line 254 of file Funcs.py.
Deltat
Deltat = Loader.getfloat("Model", "deltat")
Definition at line 258 of file Funcs.py.
eta
eta
Definition at line 254 of file Funcs.py.
field
field = Field(length_m=length_m, width_m=width_m, rows = rows, cols = cols, rx = rx, ry = ry, alpha = alpha, beta = beta, Wm = wm, Deltat = Deltat)
Definition at line 261 of file Funcs.py.
gamma
gamma
Definition at line 254 of file Funcs.py.
length_m
length_m
Definition at line 256 of file Funcs.py.
lmbda
lmbda
Definition at line 254 of file Funcs.py.
Loader
Loader = ConfigLoader('../config.ini')
Definition at line 252 of file Funcs.py.
mr
mr
Definition at line 254 of file Funcs.py.
ms
ms
Definition at line 254 of file Funcs.py.
rows
rows
Definition at line 256 of file Funcs.py.
rx
rx
Definition at line 256 of file Funcs.py.
ry
ry
Definition at line 256 of file Funcs.py.
v
v
Definition at line 254 of file Funcs.py.
width_m
width_m
Definition at line 256 of file Funcs.py.
wm
wm
Definition at line 254 of file Funcs.py.
wp
wp
Definition at line 254 of file Funcs.py.