Diplom: ConfigLoader Class Reference
ConfigLoader Class Reference
ConfigLoader class.
Public Member Functions
__init__ (self, str config_file)
Constructor.
str get (self, str section, str key, str default=None)
Retrieve a value from the configuration.
int getint (self, str section, str key, int default=None)
Retrieve an integer value from the configuration.
float getfloat (self, str section, str key, float default=None)
Retrieve a float value from the configuration.
bool getboolean (self, str section, str key, bool default=None)
Retrieve a boolean value from the configuration.
None set (self, str section, str key, str value)
Set a value in the configuration.
None save (self)
Save the configuration to the file.
None print_config (self)
Print the configuration to the console.
Data Fields
config_file = config_file
config = ConfigParser()
Protected Member Functions
_get_section (self, str section)
Retrieve all key-value pairs in a section of the configuration file.
Detailed Description
ConfigLoader class.
Class for loading and managing configuration files.
Definition at line 11 of file ConfigLoader.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, str config_file)
Constructor.
Parameters
config_file Path to the configuration file.
Definition at line 18 of file ConfigLoader.py.
References _get_section(), config, and config_file.
Member Function Documentation
_get_section()
_get_section (self, str section) protected
Retrieve all key-value pairs in a section of the configuration file.
Parameters
section The section name to retrieve the key-value pairs for.
Returns
A dictionary containing all key-value pairs in the specified section.
Definition at line 37 of file ConfigLoader.py.
References config, and get().
Referenced by __init__().
get()
str get (self, str section, str key, str default = None)
Retrieve a value from the configuration.
Parameters
section The section in the configuration file.
key The key within the section to retrieve the value for.
default The default value to return if the section or key is not found.
Returns
The value associated with the specified section and key, or the default value if an error occurs.
Definition at line 50 of file ConfigLoader.py.
References config, and get().
Referenced by _get_section(), and get().
getboolean()
bool getboolean (self, str section, str key, bool default = None)
Retrieve a boolean value from the configuration.
Parameters
section The section in the configuration file.
key The key within the section to retrieve the boolean value for.
default The default value to return if the section or key is not found, or if the value cannot be converted to a boolean.
Returns
The boolean value associated with the specified section and key, or the default value if an error occurs.
Definition at line 99 of file ConfigLoader.py.
References config, and getboolean().
Referenced by getboolean().
getfloat()
float getfloat (self, str section, str key, float default = None)
Retrieve a float value from the configuration.
Parameters
section The section in the configuration file.
key The key within the section to retrieve the float value for.
default The default value to return if the section or key is not found, or if the value cannot be converted to a float.
Returns
The float value associated with the specified section and key, or the default value if an error occurs.
Definition at line 82 of file ConfigLoader.py.
References config, and getfloat().
Referenced by getfloat().
getint()
int getint (self, str section, str key, int default = None)
Retrieve an integer value from the configuration.
Parameters
section The section in the configuration file.
key The key within the section to retrieve the integer value for.
default The default value to return if the section or key is not found, or if the value cannot be converted to an integer.
Returns
The integer value associated with the specified section and key, or the default value if an error occurs.
Definition at line 66 of file ConfigLoader.py.
References config, and getint().
Referenced by getint().
print_config()
None print_config (self)
Print the configuration to the console.
Returns
None
Definition at line 144 of file ConfigLoader.py.
References config.
save()
None save (self)
Save the configuration to the file.
This method saves the current configuration to the file specified in self.config_file. The configuration is written to the file in the format specified in the ConfigParser
Returns
None
Definition at line 130 of file ConfigLoader.py.
References config, and config_file.
set()
None set (self, str section, str key, str value)
Set a value in the configuration.
Parameters
section The section in the configuration file.
key The key within the section to set the value for.
value The value to set.
Returns
None
Definition at line 115 of file ConfigLoader.py.
References config, and set().
Referenced by set().
Field Documentation
config
config = ConfigParser()
Definition at line 31 of file ConfigLoader.py.
Referenced by __init__(), _get_section(), get(), getboolean(), getfloat(), getint(), print_config(), save(), and set().
config_file
config_file = config_file
Definition at line 30 of file ConfigLoader.py.
Referenced by __init__(), and save().
The documentation for this class was generated from the following file:
ConfigLoader.py